"""empty message

Revision ID: 96a3bf62dfc2
Revises: c3c2e1c4a547
Create Date: 2024-01-08 14:48:08.792302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a3bf62dfc2'
down_revision = 'c3c2e1c4a547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mood_type', sa.Enum('happy', 'sad', 'angry', 'surprised', 'neutral', 'relaxed', 'exhausted', 'tired', 'motivated', 'thankful', 'stressed', 'lost', 'frightened', 'excited', 'confused'), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mood')
    # ### end Alembic commands ###
