"""empty message

Revision ID: ceaeb44f7bd2
Revises: cfb007773bd8
Create Date: 2024-01-13 18:13:06.238080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceaeb44f7bd2'
down_revision = 'cfb007773bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('last_name')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('name')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
