"""empty message

Revision ID: d949d4e8c338
Revises: b8a633a49b2e
Create Date: 2023-12-27 22:59:45.021006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd949d4e8c338'
down_revision = 'b8a633a49b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('birth_date', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('username')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
